spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:postgresql://localhost:5435/transaction_db
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      platform: postgres

server:
  port: 0

wallet:
  service:
    name: wallet-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
