spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: wallet-service
          uri: lb://wallet-service
          predicates:
            - Path=/api/wallet/**
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/transaction/**
        - id: price-service
          uri: lb://price-service
          predicates:
            - Path=/api/price/**
        - id: discovery-service
          uri: lb://discovery-service
          predicates:
            - Path=/eureka/web
            - Path=/eureka/**
          filters:
            - SetPath=/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080
