spring:
datasource:
url: jdbc:postgresql://localhost:5432/wallet_db
username: postgres
password: postgres
jpa:
hibernate:
ddl-auto: update  # Automatically updates the database schema
show-sql: true

eureka:
client:
service-url:
defaultZone: http://localhost:8761/eureka/

server:
port: 8081
